services:
  - type: web
    name: canslim-quant-scanner
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT wsgi:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_HOST
        value: 0.0.0.0
      - key: FLASK_PORT
        value: 10000
      - key: IS_MOCK
        value: true
